apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gmndc-letsencrypt-certificate
  namespace: default
spec:
  secretName: gmndc-letsencrypt-certificate-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - homekube-io
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - gmndc.lk
  issuerRef:
    name: gmndc-letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io