apiVersion: v1
kind: Service
metadata:
  name: gmndc-web-service
  labels:
    app: gmndc-web-service
    service: gmndc-web-service
spec:
  ports:
   - name: http
     protocol : TCP
     port: 80
     targetPort: 80
  selector:
    app: gmndc-web
